version: "3.9"

networks:
  dedupphoto:
    external: false

services:
  dedupphoto:
    image: happyzyz/dedupphoto:latest
    ports:
      - "8989:8888"
    restart: on-failure:5
    volumes:
      - <some volume>:/myfolder:rw
      - <some volume>:/mytrashbin:rw
    networks:
      - dedupphoto